<table class='chessboard'>
    <tr id='rank_8'>
        <td class='black' id='a8'></td>
        <td class='white' id='b8'></td>
        <td class='black' id='c8'></td>
        <td class='white' id='d8'></td>
        <td class='black' id='e8'></td>
        <td class='white' id='f8'></td>
        <td class='black' id='g8'></td>
        <td class='white' id='h8'></td>
    </tr>
    <tr id='rank_7'>
        <td class='white' id='a7'></td>
        <td class='black' id='b7'></td>
        <td class='white' id='c7'></td>
        <td class='black' id='d7'></td>
        <td class='white' id='e7'></td>
        <td class='black' id='f7'></td>
        <td class='white' id='g7'></td>
        <td class='black' id='h7'></td>
    </tr>
    <tr id='rank_6'>
        <td class='black' id='a6'></td>
        <td class='white' id='b6'></td>
        <td class='black' id='c6'></td>
        <td class='white' id='d6'></td>
        <td class='black' id='e6'></td>
        <td class='white' id='f6'></td>
        <td class='black' id='g6'></td>
        <td class='white' id='h6'></td>
    </tr>
    <tr id='rank_5'>
        <td class='white' id='a5'></td>
        <td class='black' id='b5'></td>
        <td class='white' id='c5'></td>
        <td class='black' id='d5'></td>
        <td class='white' id='e5'></td>
        <td class='black' id='f5'></td>
        <td class='white' id='g5'></td>
        <td class='black' id='h5'></td>
    </tr>
    <tr id='rank_4'>
        <td class='black' id='a4'></td>
        <td class='white' id='b4'></td>
        <td class='black' id='c4'></td>
        <td class='white' id='d4'></td>
        <td class='black' id='e4'></td>
        <td class='white' id='f4'></td>
        <td class='black' id='g4'></td>
        <td class='white' id='h4'></td>
    </tr>
    <tr id='rank_3'>
        <td class='white' id='a3'></td>
        <td class='black' id='b3'></td>
        <td class='white' id='c3'></td>
        <td class='black' id='d3'></td>
        <td class='white' id='e3'></td>
        <td class='black' id='f3'></td>
        <td class='white' id='g3'></td>
        <td class='black' id='h3'></td>
    </tr>
    <tr id='rank_2'>
        <td class='black' id='a2'></td>
        <td class='white' id='b2'></td>
        <td class='black' id='c2'></td>
        <td class='white' id='d2'></td>
        <td class='black' id='e2'></td>
        <td class='white' id='f2'></td>
        <td class='black' id='g2'></td>
        <td class='white' id='h2'></td>
    </tr>
    <tr id='rank_1'>
        <td class='white' id='a1'></td>
        <td class='black' id='b1'></td>
        <td class='white' id='c1'></td>
        <td class='black' id='d1'></td>
        <td class='white' id='e1'></td>
        <td class='black' id='f1'></td>
        <td class='white' id='g1'></td>
        <td class='black' id='h1'></td>
    </tr>
</table>
<div id="menu">
    <div id="game">
        <input id='newGameButton' type='button' value='New game'/>
    </div>
</div>